CREATE TABLE machinists(
	uniqname VARCHAR(20) NOT NULL,
  password VARCHAR(256) NOT NULL,
	fullname VARCHAR(40) NOT NULL,
	filename VARCHAR(256),
	millStatus VARCHAR(40),
  latheStatus VARCHAR(40),
  cncMillStatus VARCHAR(40),
  cncLatheStatus VARCHAR(40),
  haasStatus VARCHAR(40),
	available VARCHAR(40),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(uniqname)
);

CREATE TABLE parts(
	name VARCHAR(20) NOT NULL,
	number VARCHAR(40) NOT NULL,
	designer VARCHAR(40) NOT NULL,
  machinist VARCHAR(64) NOT NULL,
  designCheck VARCHAR(40) NOT NULL,
  productionCheck VARCHAR(40) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(number)
);

CREATE TABLE ops(
	name VARCHAR(128) NOT NULL,
	number VARCHAR(20) NOT NULL,
	designer VARCHAR(40) NOT NULL,
	machinist VARCHAR(64) NOT NULL,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(number),
  FOREIGN KEY(number) REFERENCES parts(number)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);